title: Zachary Mathews
author: Zachary Mathews
email: zachary.c.mathews+blog@gmail.com
description: >
  Blog focused on development of Revit add-ins and automating repetitive tasks across
  multiple disciplines.
show_excerpts: true

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Zachary Mathews
  tagline: |
    Electrical Designer.
    Add-in Developer.
    BIM Manager.
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  disqus_shortname: zacharymathews
  analytics_id: "UA-27240029-6"

  # generate social links in footer
  social_links:
    # twitter: zcmathews
    github:  zachcmathews
    linkedIn: in/zachcmathews
    # rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
remote_theme: thelehhman/plainwhite-jekyll

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
